In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
import risk_kit as rk

In [3]:
hfi = rk.get_hfi_returns()
hfi.head()

<string>:5: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.

,Convertible Arbitrage,CTA Global,Distressed Securities,Emerging Markets,Equity Market Neutral,Event Driven,Fixed Income Arbitrage,Global Macro,Long/Short Equity,Merger Arbitrage,Relative Value,Short Selling,Funds Of Funds
date,,,,,,,,,,,,,
1997-01,0.0119,0.0393,0.0178,0.0791,0.0189,0.0213,0.0191,0.0573,0.0281,0.0150,0.0180,-0.0166,0.0317
1997-02,0.0123,0.0298,0.0122,0.0525,0.0101,0.0084,0.0122,0.0175,-0.0006,0.0034,0.0118,0.0426,0.0106
1997-03,0.0078,-0.0021,-0.0012,-0.0120,0.0016,-0.0023,0.0109,-0.0119,-0.0084,0.0060,0.0010,0.0778,-0.0077
1997-04,0.0086,-0.0170,0.0030,0.0119,0.0119,-0.0005,0.0130,0.0172,0.0084,-0.0001,0.0122,-0.0129,0.0009
1997-05,0.0156,-0.0015,0.0233,0.0315,0.0189,0.0346,0.0118,0.0108,0.0394,0.0197,0.0173,-0.0737,0.0275

In [5]:
pd.concat([hfi.mean(), hfi.median(), hfi.mean() > hfi.median()], axis = 'columns')

                               0       1      2
Convertible Arbitrage   0.005508  0.0065  False
CTA Global              0.004074  0.0014   True
Distressed Securities   0.006946  0.0089  False
Emerging Markets        0.006253  0.0096  False
Equity Market Neutral   0.004498  0.0051  False
Event Driven            0.006344  0.0084  False
Fixed Income Arbitrage  0.004365  0.0055  False
Global Macro            0.005403  0.0038   True
Long/Short Equity       0.006331  0.0079  False
Merger Arbitrage        0.005356  0.0060  False
Relative Value          0.005792  0.0067  False
Short Selling          -0.001701 -0.0053   True
Funds Of Funds          0.004262  0.0052  False

In [6]:
rk.skewness(hfi).sort_values()

Fixed Income Arbitrage   -3.940320
Convertible Arbitrage    -2.639592
Equity Market Neutral    -2.124435
Relative Value           -1.815470
Event Driven             -1.409154
Merger Arbitrage         -1.320083
Distressed Securities    -1.300842
Emerging Markets         -1.167067
Long/Short Equity        -0.390227
Funds Of Funds           -0.361783
CTA Global                0.173699
Short Selling             0.767975
Global Macro              0.982922
dtype: float64

In [7]:
import scipy.stats

In [10]:
scipy.stats.skew(hfi)

array([-2.63959223,  0.17369864, -1.30084204, -1.16706749, -2.12443538,
       -1.40915356, -3.94032029,  0.98292188, -0.39022677, -1.32008333,
       -1.81546975,  0.76797484, -0.36178308])

In [11]:
import numpy as np

In [18]:
normal_rets = np.random.normal(0, .15, size = (hfi.shape[0], 1))

In [13]:
rk.skewness(normal_rets)

np.float64(0.12412233140516324)

In [15]:
rk.kurtosis(normal_rets)

np.float64(2.7158206569632717)

In [16]:
rk.kurtosis(hfi)

Convertible Arbitrage     23.280834
CTA Global                 2.952960
Distressed Securities      7.889983
Emerging Markets           9.250788
Equity Market Neutral     17.218555
Event Driven               8.035828
Fixed Income Arbitrage    29.842199
Global Macro               5.741679
Long/Short Equity          4.523893
Merger Arbitrage           8.738950
Relative Value            12.121208
Short Selling              6.117772
Funds Of Funds             7.070153
dtype: float64

In [17]:
scipy.stats.kurtosis(normal_rets)

array([-0.28417934])

In [19]:
scipy.stats.jarque_bera(normal_rets)

SignificanceResult(statistic=np.float64(1.0320514969932886), pvalue=np.float64(0.5968880235072223))

In [21]:
rk.is_normal(hfi)

np.False_

In [24]:
hfi.aggregate(rk.is_normal)

Convertible Arbitrage     False
CTA Global                 True
Distressed Securities     False
Emerging Markets          False
Equity Market Neutral     False
Event Driven              False
Fixed Income Arbitrage    False
Global Macro              False
Long/Short Equity         False
Merger Arbitrage          False
Relative Value            False
Short Selling             False
Funds Of Funds            False
dtype: bool

In [26]:
rk.is_normal(normal_rets)

np.True_

In [27]:
ffme = rk.get_ffme_returns()
rk.skewness(ffme)

C:\Users\Yifei\anaconda_projects\Investment Management with Python and Machine Learning Specialization\risk_kit.py:26: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  me_m = pd.read_csv('data/Portfolios_Formed_on_ME_monthly_EW.csv',

SmallCap    4.410739
LargeCap    0.233445
dtype: float64

In [28]:
rk.kurtosis(ffme)

SmallCap    46.845008
LargeCap    10.694654
dtype: float64

In [30]:
ffme.aggregate(rk.is_normal)

SmallCap    False
LargeCap    False
dtype: bool