In [1]:
import pandas as pd
import numpy as np
import risk_kit as rk

In [2]:
me_m = pd.read_csv('data/Portfolios_Formed_on_ME_monthly_EW.csv',
                    header = 0, index_col = 0, 
                    parse_dates = True, na_values = -99.99
                    )
rets = me_m[['Lo 20', 'Hi 20']] / 100
rets.columns = ['SmallCap', 'LargeCap']
rets.index = pd.to_datetime(rets.index, format = '%Y%m').to_period('M')
rets.head()

C:\Users\Yifei\AppData\Local\Temp\ipykernel_1472\3282002452.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  me_m = pd.read_csv('data/Portfolios_Formed_on_ME_monthly_EW.csv',

         SmallCap  LargeCap
1926-07   -0.0057    0.0333
1926-08    0.0384    0.0233
1926-09   -0.0048   -0.0009
1926-10   -0.0329   -0.0295
1926-11   -0.0055    0.0316

## Q1 & Q3

In [11]:
annualized_rets = (((rets + 1).prod()**(12 / rets.shape[0]) - 1) * 100).round(2)
annualized_rets

SmallCap    15.20
LargeCap     9.85
dtype: float64

## Q2 & Q4

In [15]:
annulized_vol = (rets.std(ddof = 0) * np.sqrt(12) * 100).round(1) 
annulized_vol

SmallCap    33.7
LargeCap    19.5
dtype: float64

## Q5 & Q7

In [17]:
annualized_rets = (((rets.loc['1999':'2015'] + 1).prod()**(12 / rets.loc['1999':'2015'].shape[0]) - 1) * 100).round(2)
annualized_rets

SmallCap    11.44
LargeCap     6.29
dtype: float64

In [18]:
annulized_vol = (rets.loc['1999':'2015'].std(ddof = 0) * np.sqrt(12) * 100).round(1) 
annulized_vol

SmallCap    22.8
LargeCap    17.2
dtype: float64

## Q9 & Q10

In [31]:
maxDD = -rk.drawdown(rets.loc['1999':'2015']['SmallCap'])['Drawdowns'].min() * 100
maxDD = round(maxDD, 2)
maxDD

62.48

In [32]:
maxDD_date = rk.drawdown(rets.loc['1999':'2015']['SmallCap'])['Drawdowns'].idxmin()
maxDD_date

Period('2009-02', 'M')

## Q11 & Q12

In [33]:
maxDD = -rk.drawdown(rets.loc['1999':'2015']['LargeCap'])['Drawdowns'].min() * 100
maxDD = round(maxDD, 2)
maxDD

55.27

In [34]:
maxDD_date = rk.drawdown(rets.loc['1999':'2015']['LargeCap'])['Drawdowns'].idxmin()
maxDD_date

Period('2009-02', 'M')

## Q13 ~ Q16

In [37]:
hfi = rk.get_hfi_returns()
hfi = hfi.loc['2009':'2018']
hfi.head()

C:\Users\Yifei\anaconda_projects\Investment Management with Python and Machine Learning Specialization\risk_kit.py:41: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  hfi = pd.read_csv('data/edhec-hedgefundindices.csv',

,Convertible Arbitrage,CTA Global,Distressed Securities,Emerging Markets,Equity Market Neutral,Event Driven,Fixed Income Arbitrage,Global Macro,Long/Short Equity,Merger Arbitrage,Relative Value,Short Selling,Funds Of Funds
date,,,,,,,,,,,,,
2009-01,0.0491,-0.0016,0.0082,-0.0112,0.0079,0.0132,0.0112,0.0029,-0.0017,0.0056,0.0100,0.0282,0.0060
2009-02,0.0164,-0.0031,-0.0122,-0.0133,-0.0046,-0.0091,0.0065,-0.0055,-0.0161,0.0006,-0.0016,0.0328,-0.0037
2009-03,0.0235,-0.0180,0.0022,0.0350,0.0021,0.0117,0.0057,0.0048,0.0188,0.0125,0.0100,-0.0462,0.0008
2009-04,0.0500,-0.0140,0.0387,0.0663,-0.0012,0.0337,0.0221,0.0127,0.0375,0.0081,0.0342,-0.0820,0.0092
2009-05,0.0578,0.0213,0.0504,0.0884,0.0146,0.0442,0.0365,0.0348,0.0516,0.0107,0.0392,0.0008,0.0312

In [40]:
rk.semideviation(hfi).idxmax()

'Short Selling'

In [41]:
rk.semideviation(hfi).idxmin()

'Fixed Income Arbitrage'

In [44]:
rk.skewness(hfi).idxmin()

'Equity Market Neutral'

In [46]:
rk.kurtosis(rk.get_hfi_returns().loc['2000':'2018']).idxmax()

C:\Users\Yifei\anaconda_projects\Investment Management with Python and Machine Learning Specialization\risk_kit.py:41: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  hfi = pd.read_csv('data/edhec-hedgefundindices.csv',

'Fixed Income Arbitrage'