In [1]:
import numpy as np
import pandas as pd
import risk_kit as rk
import statsmodels.api as sm
%load_ext autoreload
%autoreload 2

In [2]:
ind = rk.get_ind_returns(weighting='vw', n_inds=49)
fff = rk.get_fff_returns()

In [3]:
ind.head()

,Agric,Food,Soda,Beer,Smoke,Toys,Fun,Books,Hshld,Clths,...,Boxes,Trans,Whlsl,Rtail,Meals,Banks,Insur,RlEst,Fin,Other
1926-07,0.0237,0.0012,NaN,-0.0519,0.0129,0.0865,0.0250,0.5021,-0.0048,0.0808,...,0.0770,0.0194,-0.2379,0.0007,0.0187,0.0461,-0.0054,0.0289,-0.0485,0.0520
1926-08,0.0223,0.0268,NaN,0.2703,0.0650,0.1681,-0.0076,0.4298,-0.0358,-0.0251,...,-0.0238,0.0488,0.0539,-0.0075,-0.0013,0.1183,0.0257,0.0530,-0.0057,0.0676
1926-09,-0.0057,0.0158,NaN,0.0402,0.0126,0.0833,0.0642,-0.0491,0.0073,-0.0051,...,-0.0554,0.0006,-0.0787,0.0025,-0.0056,-0.0175,0.0072,-0.0306,-0.0314,-0.0386
1926-10,-0.0046,-0.0368,NaN,-0.0331,0.0106,-0.0140,-0.0509,0.0537,-0.0468,0.0012,...,-0.0508,-0.0264,-0.1538,-0.0220,-0.0411,-0.1182,-0.0428,-0.0574,0.0207,-0.0849
1926-11,0.0675,0.0626,NaN,0.0729,0.0455,0.0000,0.0182,-0.0640,-0.0054,0.0187,...,0.0384,0.0160,0.0467,0.0652,0.0433,-0.0297,0.0358,0.0221,0.0492,0.0400

In [4]:
fff.head()

         Mkt-RF     SMB     HML      RF
1926-07  0.0296 -0.0230 -0.0287  0.0022
1926-08  0.0264 -0.0140  0.0419  0.0025
1926-09  0.0036 -0.0132  0.0001  0.0023
1926-10 -0.0324  0.0004  0.0051  0.0032
1926-11  0.0253 -0.0020 -0.0035  0.0031

In [5]:
ind_excess = ind.loc['1991':'2018'] - fff.loc['1991':'2018', ['RF']].values
mkt_excess = fff.loc['1991':'2018', ['Mkt-RF']]
exp_var = mkt_excess.copy()
exp_var['Constant'] = 1
lm = sm.OLS(ind_excess['Beer'], exp_var).fit()
lm.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                   Beer   R-squared:                       0.226
Model:                            OLS   Adj. R-squared:                  0.224
Method:                 Least Squares   F-statistic:                     97.55
Date:                Wed, 18 Feb 2026   Prob (F-statistic):           2.37e-20
Time:                        20:10:21   Log-Likelihood:                 596.94
No. Observations:                 336   AIC:                            -1190.
Df Residuals:                     334   BIC:                            -1182.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Mkt-RF         0.5295      0.054      9.877      0.000       0.424       0.635
Constant       0.0043      0.002      1.892      0.059      -0.000       0.009
==============================================================================
Omnibus:                       20.697   Durbin-Watson:                   2.079
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               43.130
Skew:                          -0.314   Prob(JB):                     4.31e-10
Kurtosis:                       4.639   Cond. No.                         23.9
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [6]:
lm.params['Mkt-RF'].round(2)

np.float64(0.53)

In [7]:
lm_steel = sm.OLS(ind_excess['Steel'], exp_var).fit()
lm_steel.params['Mkt-RF'].round(2)

np.float64(1.55)

In [8]:
ind_excess = ind.loc['2013':'2018'] - fff.loc['2013':'2018', ['RF']].values
mkt_excess = fff.loc['2013':'2018', ['Mkt-RF']]
exp_var = mkt_excess.copy()
exp_var['Constant'] = 1
lm_beer_13_18 = sm.OLS(ind_excess['Beer'], exp_var).fit()
lm_beer_13_18.params['Mkt-RF'].round(2)

np.float64(0.59)

In [9]:
lm_steel_13_18 = sm.OLS(ind_excess['Steel'], exp_var).fit()
lm_steel_13_18.params['Mkt-RF'].round(2)

np.float64(1.42)

In [10]:
ind_excess = ind.loc['1991':'1993'] - fff.loc['1991':'1993', ['RF']].values
mkt_excess = fff.loc['1991':'1993', ['Mkt-RF']]
exp_var = mkt_excess.copy()
exp_var['Constant'] = 1

In [11]:
ind_betas = {industries: sm.OLS(ind_excess[industries], exp_var).fit().params['Mkt-RF'] for industries in ind_excess.columns}
ind_betas

{'Agric': np.float64(1.0283814931320745),
 'Food': np.float64(1.2626090934157992),
 'Soda': np.float64(1.3190354951579866),
 'Beer': np.float64(1.198077867097216),
 'Smoke': np.float64(1.3237761410983233),
 'Toys': np.float64(1.0575959185826227),
 'Fun': np.float64(1.0286742236318545),
 'Books': np.float64(0.9868289248059069),
 'Hshld': np.float64(1.0141781818331543),
 'Clths': np.float64(1.5169272931029651),
 'Hlth': np.float64(1.615195497113445),
 'MedEq': np.float64(1.4739253526115008),
 'Drugs': np.float64(1.248731648219112),
 'Chems': np.float64(0.888434125801439),
 'Rubbr': np.float64(1.1694505038735654),
 'Txtls': np.float64(1.1306683202661203),
 'BldMt': np.float64(1.1717739827745852),
 'Cnstr': np.float64(1.5208822919484473),
 'Steel': np.float64(0.9462051336916991),
 'FabPr': np.float64(1.2452483578760094),
 'Mach': np.float64(1.0900680247122319),
 'ElcEq': np.float64(1.217794171440993),
 'Autos': np.float64(0.7477211103786134),
 'Aero': np.float64(0.7934918670395721),
 'Ships': np.float64(1.2097026468549317),
 'Guns': np.float64(0.561699341398857),
 'Gold': np.float64(-0.5532887150791106),
 'Mines': np.float64(0.2747615592764885),
 'Coal': np.float64(0.5299575583256863),
 'Oil': np.float64(0.5506038162933444),
 'Util': np.float64(0.3795274131100522),
 'Telcm': np.float64(0.7158672413918185),
 'PerSv': np.float64(0.9720243363027062),
 'BusSv': np.float64(1.028504885671388),
 'Hardw': np.float64(1.0220695856801392),
 'Softw': np.float64(1.608340021997596),
 'Chips': np.float64(1.272862895791537),
 'LabEq': np.float64(1.2530216303592183),
 'Paper': np.float64(0.7172023055320838),
 'Boxes': np.float64(0.6338168887394701),
 'Trans': np.float64(1.1683752306992796),
 'Whlsl': np.float64(1.0321154899268752),
 'Rtail': np.float64(1.2273977121271669),
 'Meals': np.float64(1.1453428825738954),
 'Banks': np.float64(1.3592332290879878),
 'Insur': np.float64(0.9360935464460174),
 'RlEst': np.float64(0.5992480571066948),
 'Fin': np.float64(1.0915408270816302),
 'Other': np.float64(1.4548260109642897)}

In [12]:
max(ind_betas, key=ind_betas.get)

'Hlth'

In [13]:
min(ind_betas, key=ind_betas.get)

'Gold'

In [23]:
ind_excess = ind.loc['1991':'2018'] - fff.loc['1991':'2018', ['RF']].values
exp_var = fff.loc['1991':'2018', ['Mkt-RF', 'SMB', 'HML']]
size_coef = {industries : rk.regress(ind_excess[industries], exp_var).params['SMB'] for industries in ind_excess.columns}

In [24]:
max(size_coef, key=size_coef.get)

'FabPr'

In [25]:
min(size_coef, key=size_coef.get)

'Beer'

In [26]:
value_coef = {industries : rk.regress(ind_excess[industries], exp_var).params['HML'] for industries in ind_excess.columns}

In [27]:
max(size_coef, key=value_coef.get)

'Txtls'

In [28]:
min(size_coef, key=value_coef.get)

'Softw'